### ISSUE TITLE
Time zone config

### ISSUE THREAD

**Issue by zmoon** [noaa-oar-arl/NEXUS#11]
[It seems](https://web.archive.org/web/20200807020453/http://wiki.seas.harvard.edu/geos-chem/index.php/HEMCO_versions#Ocean_grid_boxes_now_use_the_timezone_of_the_nearest_land_mass_for_computing_emissions) that the timezone file specified in `NEXUS_Config.rc` is not the recommended one. The recommended `timezones_voronoi_1x1.nc` allegedly does better for coastal grid cells that have ocean overlap. Has this been tried in NEXUS?

**Comment by bbakernoaa** [comment]
I haven't tried it but there is no reason to think it wouldn't work
