### ISSUE TITLE
NEUX job failed with harsh  # c7b9af5

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [noaa-oar-arl/NEXUS#36]
I checked out the latest NEXUS code on Cactus.

Here the arl_nexus code log information
commit c7b9af568b32acf47c1b97fad6deabef3fe487aa
Merge: 6a7a994 72c51f5
Author: Barry Baker <bbakernoaa@users.noreply.github.com>
Date:   Thu Jun 29 15:34:48 2023 -0400
    Merge pull request #35 from noaa-oar-arl/feature/add_soilnox
     Feature/add soilnox
=============

However, the nexus jobs failed with the following error message.

**Traceback (most recent call last):
  File "/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.82a/sorc/arl_nexus/utils/python/nexus_gfs_bio.py", line 428, in <module>
    raise SystemExit(main(**parse_args()))
  File "/lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.82a/sorc/arl_nexus/utils/python/nexus_gfs_bio.py", line 171, in main
    assert len(files) >= 2, "need at least 2 for time interp and time calcs"
AssertionError: need at least 2 for time interp and time calcs**

More details can be found at 
/lfs/h2/emc/ptmp/jianping.huang/emc.para/output/20200815 > vim nexus_emission_2020081506_s00.id_1688123510.log

**Comment by zmoon** [comment]
The error suggests that no (or 1) GFS files matched the glob [here](https://github.com/bbakernoaa/ufs-srweather-app/blob/a45aa5002f3e3dbef6394a53e80193c8d7b5877b/scripts/exregional_nexus_emission.sh#L300).

**Comment by JianpingHuang-NOAA** [comment]
Thanks @zmoon 

One more questions for you and Barry. Do we still need the follow lines of using soil NOx emissions in the ex-script, exregional_nexus_emission.sh ?

< OFFLINE_SOILNOX="TRUE"
299,302d297
< if [ "${OFFLINE_SOILNOX}" = "TRUE" ]; then #OFFLINE_SOILNOX
<   ln -sf ${NEXUS_INPUT_BASE_DIR}/OFFLINE_SOILNOX ${DATAinput}
< fi

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA yes you will need that because it links the OFFLINE_SOILNOX data to the directory.  This data should be zero for august.  I'll do a test case during this time period to test quickly
